[package]
name = "vpi_export"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Export Rust function to be used on a verilog module through VPI"

[dependencies]
ctor = "0.2.9"
proc-macro2 = "1.0.92"
vpi_export_macro = "0.1.0"

[dev-dependencies]
trybuild = "1.0.101"

[build-dependencies]
bindgen = "0.70.1"
